from __future__ import annotations

import hashlib
import json
import multiprocessing
import sqlite3
from pathlib import Path

import pytest

from zion_eval.errors import TruthIndexError
from zion_eval.truth import build_truth_index, is_placeholder_name, iter_truth_entries


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _build_worker(truth_path: str, checksum: str, cache_dir: str, queue: object) -> None:
    try:
        with build_truth_index(
            truth_path,
            cache_dir,
            truth_sha256=checksum,
            image_base=0,
            address_space="rva",
        ) as index:
            queue.put(("ok", index.count))  # type: ignore[attr-defined]
    except BaseException as exc:  # pragma: no cover - reported to parent assertion
        queue.put(("error", repr(exc)))  # type: ignore[attr-defined]


def _truth_fixture(path: Path) -> str:
    path.write_text(
        json.dumps(
            {
                "0x140001000": {
                    "name": "Widget::run()",
                    "mangled_name": "?run@Widget@@QEAAXXZ",
                },
                "0x140002000": {
                    "name": "sub_140002000",
                    "mangled_name": "sub_140002000",
                },
                "0x140003000": {
                    "name": "",
                    "mangled_name": "_ZN6Widget4stopEv",
                },
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    return _sha256(path)


def test_streaming_reader_handles_values_larger_than_one_chunk(tmp_path: Path) -> None:
    path = tmp_path / "large.json"
    long_name = "A" * (1024 * 1024 + 17)
    path.write_text(
        json.dumps({"0x1": {"name": long_name, "mangled_name": "m"}}),
        encoding="utf-8",
    )

    entries = list(iter_truth_entries(path))
    assert entries[0][0] == "0x1"
    assert entries[0][1]["name"] == long_name


def test_index_normalizes_va_and_exposes_selected_lookup_only(tmp_path: Path) -> None:
    truth_path = tmp_path / "truth.json"
    checksum = _truth_fixture(truth_path)
    cache = tmp_path / "private"

    with build_truth_index(
        truth_path,
        cache,
        truth_sha256=checksum,
        image_base=0x140000000,
        address_space="va",
    ) as index:
        assert index.path.name == f"truth-{checksum}.sqlite3"
        assert index.count == 3
        assert index.gradeable_count == 2
        selected = index.lookup_many(["0x1000", "0x2000", "0x9999"])
        assert selected["0x1000"].name == "Widget::run()"  # type: ignore[union-attr]
        assert selected["0x2000"].gradeable is False  # type: ignore[union-attr]
        assert selected["0x2000"].ungradable_reason == "autogenerated_placeholder"  # type: ignore[union-attr]
        assert selected["0x9999"] is None
        assert index.lookup("0x3000").exact_names == frozenset(  # type: ignore[union-attr]
            {"_ZN6Widget4stopEv"}
        )

    assert cache.stat().st_mode & 0o077 == 0
    assert (cache / f"truth-{checksum}.sqlite3").stat().st_mode & 0o077 == 0


def test_index_reuses_valid_checksum_cache(tmp_path: Path) -> None:
    truth_path = tmp_path / "truth.json"
    checksum = _truth_fixture(truth_path)
    cache = tmp_path / "private"
    first = build_truth_index(
        truth_path,
        cache,
        truth_sha256=checksum,
        image_base=0x140000000,
        address_space="va",
    )
    inode = first.path.stat().st_ino
    first.close()
    second = build_truth_index(
        truth_path,
        cache,
        truth_sha256=checksum,
        image_base=0x140000000,
        address_space="va",
    )
    try:
        assert second.path.stat().st_ino == inode
    finally:
        second.close()


def test_verified_cache_reopens_without_rehashing_source(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    truth_path = tmp_path / "truth.json"
    checksum = _truth_fixture(truth_path)
    cache = tmp_path / "private"
    with build_truth_index(
        truth_path,
        cache,
        truth_sha256=checksum,
        image_base=0x140000000,
        address_space="va",
    ):
        pass

    def unexpected_hash(_: Path) -> str:
        raise AssertionError("a metadata-valid verified cache must not rehash truth")

    monkeypatch.setattr("zion_eval.truth.sha256_file", unexpected_hash)
    with build_truth_index(
        truth_path,
        cache,
        truth_sha256=checksum,
        image_base=0x140000000,
        address_space="va",
    ) as reopened:
        assert reopened.count == 3


@pytest.mark.parametrize("cache_state", ["missing", "invalid"])
def test_missing_or_invalid_cache_still_verifies_source(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    cache_state: str,
) -> None:
    truth_path = tmp_path / "truth.json"
    checksum = _truth_fixture(truth_path)
    cache = tmp_path / "private"
    if cache_state == "invalid":
        with build_truth_index(
            truth_path,
            cache,
            truth_sha256=checksum,
            image_base=0x140000000,
            address_space="va",
        ) as existing:
            index_path = existing.path
        connection = sqlite3.connect(index_path)
        connection.execute(
            "UPDATE metadata SET value = '0x0' WHERE key = 'image_base'"
        )
        connection.commit()
        connection.close()

    calls = 0

    def recording_hash(path: Path) -> str:
        nonlocal calls
        calls += 1
        return _sha256(path)

    monkeypatch.setattr("zion_eval.truth.sha256_file", recording_hash)
    with build_truth_index(
        truth_path,
        cache,
        truth_sha256=checksum,
        image_base=0x140000000,
        address_space="va",
    ) as rebuilt:
        assert rebuilt.count == 3
    assert calls == 1


def test_unverified_cache_cannot_satisfy_verified_open(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    truth_path = tmp_path / "truth.json"
    checksum = _truth_fixture(truth_path)
    cache = tmp_path / "private"
    with build_truth_index(
        truth_path,
        cache,
        truth_sha256=checksum,
        image_base=0x140000000,
        address_space="va",
        verify_checksum=False,
    ):
        pass

    calls = 0

    def recording_hash(path: Path) -> str:
        nonlocal calls
        calls += 1
        return _sha256(path)

    monkeypatch.setattr("zion_eval.truth.sha256_file", recording_hash)
    with build_truth_index(
        truth_path,
        cache,
        truth_sha256=checksum,
        image_base=0x140000000,
        address_space="va",
    ):
        pass
    assert calls == 1


def test_concurrent_builders_share_one_complete_index(tmp_path: Path) -> None:
    truth_path = tmp_path / "truth.json"
    truth_path.write_text(
        json.dumps(
            {
                f"0x{address:x}": {"name": f"function_{address}x", "mangled_name": None}
                for address in range(1, 101)
            }
        ),
        encoding="utf-8",
    )
    checksum = _sha256(truth_path)
    cache = tmp_path / "private"
    context = multiprocessing.get_context("spawn")
    queue = context.Queue()
    processes = [
        context.Process(
            target=_build_worker,
            args=(str(truth_path), checksum, str(cache), queue),
        )
        for _ in range(3)
    ]
    for process in processes:
        process.start()
    results = [queue.get(timeout=30) for _ in processes]
    for process in processes:
        process.join(timeout=30)

    assert results == [("ok", 100)] * 3
    assert all(process.exitcode == 0 for process in processes)


def test_duplicate_normalized_truth_address_is_rejected(tmp_path: Path) -> None:
    truth_path = tmp_path / "duplicates.json"
    truth_path.write_text(
        '{"0x1":{"name":"one"},"0X01":{"name":"also one"}}',
        encoding="utf-8",
    )

    with pytest.raises(TruthIndexError, match="duplicate raw or normalized"):
        build_truth_index(
            truth_path,
            tmp_path / "cache",
            truth_sha256=_sha256(truth_path),
            image_base=0,
            address_space="rva",
        )


def test_truth_checksum_mismatch_is_fatal(tmp_path: Path) -> None:
    truth_path = tmp_path / "truth.json"
    truth_path.write_text("{}", encoding="utf-8")

    with pytest.raises(TruthIndexError, match="SHA-256 mismatch"):
        build_truth_index(
            truth_path,
            tmp_path / "cache",
            truth_sha256="0" * 64,
            image_base=0,
            address_space="rva",
        )


@pytest.mark.parametrize(
    "name, expected",
    [
        ("sub_142F0F430", True),
        ("FUN_0010a000", True),
        ("thunk_FUN_0010a000", True),
        ("fcn.00401000", True),
        ("function_call", False),
        ("Widget::sub_1400()", False),
    ],
)
def test_placeholder_policy_is_conservative(name: str, expected: bool) -> None:
    assert is_placeholder_name(name) is expected
